POST http://127.0.0.1:8000/auth/users/
Content-Type: application/json

{
    "username": "testuserCareGiver8",
    "email": "testuser@test.com",
    "first_name": "car1",
    "last_name": "giv1",
    "password": "perawat1234",
    "tenant": "1",
    "role": "caregiver"
}
###
GET http://127.0.0.1:8000/auth/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMzQ0NTE1LCJpYXQiOjE3NjAzNDI3MTUsImp0aSI6ImYxZWE0YjRjNDljODRkMDdhNDg1MzAwOTZlZmE2YmM2IiwidXNlcl9pZCI6IjEifQ.lYFZwoeoSxofLHqd6x2Cz4Pe38eIZHKxM1Q_AwXFmX4
###
GET http://127.0.0.1:8000/auth/users/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMDEyMzIzLCJpYXQiOjE3NjEwMTA1MjMsImp0aSI6IjcxZmZiZThjMTQ5ZjQ0MzA5Y2E3ZTJjNTVjN2Q5YjZhIiwidXNlcl9pZCI6IjExIn0.NtnmnTBlYrRYo4H36t9l6seNgfTnmPFOQz3Z_AONrK0
### LOGIN ADMIN
POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
    "username": "lfcyk",
    "password": "lemon123"   
}
### LOGIN FAMILY
POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
    "username": "testuserfam2",
    "password": "pasien1234"   
}
### LOGIN CAREGIVER
POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
    "username": "testuserCareGiver8",
    "password": "perawat1234"   
}
### Refresh TOKEN
POST http://127.0.0.1:8000/auth/jwt/refresh/
Content-Type: application/json
{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MDM0NzkxNSwiaWF0IjoxNzYwMzQyNzE1LCJqdGkiOiJlY2I3Y2JiY2EwZTQ0NDk0YmI4Y2EwNmQzZTg3ZjI1ZiIsInVzZXJfaWQiOiIxIn0.oU7ZKXo3F1bX1j1Z5v1nX1KX1Z1Z1Z1Z1Z1Z1Z1Z1Z1Z"
}
###