POST http://127.0.0.1:8000/auth/users/
Content-Type: application/json

{
    "username": "testuserCareGiver8",
    "email": "testuser@test.com",
    "first_name": "car1",
    "last_name": "giv1",
    "password": "perawat1234",
    "tenant": "1",
    "role": "caregiver"
}
###
GET http://127.0.0.1:8000/auth/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMzQ0NTE1LCJpYXQiOjE3NjAzNDI3MTUsImp0aSI6ImYxZWE0YjRjNDljODRkMDdhNDg1MzAwOTZlZmE2YmM2IiwidXNlcl9pZCI6IjEifQ.lYFZwoeoSxofLHqd6x2Cz4Pe38eIZHKxM1Q_AwXFmX4
### LOGIN ADMIN
POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
    "username": "lfcyk",
    "password": "lemon123"   
}
### LOGIN FAMILY
POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
    "username": "testuserfam2",
    "password": "pasien1234"   
}
### LOGIN CAREGIVER
POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
    "username": "testuserCareGiver8",
    "password": "perawat1234"   
}
