### Create CareNote
POST http://127.0.0.1:8000/api/carenotes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMTE3MTg2LCJpYXQiOjE3NjExMTUzODYsImp0aSI6IjhiMzQxZTY0MGIwMjQzMmM4YWM1N2JmMzdjNDA4MzY0IiwidXNlcl9pZCI6IjMifQ.OAirEmK4fOxZJuRMSbngPxuDC1RV2bOACEh6YF1zrcs

{
    "text": "Yamada-san bench 305 last night. but felt a bit dizzy in the morning.",
    "family": 1
}
### 
### Get All CareNotes
GET http://127.0.0.1:8000/api/carenotes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNzIzMjY3LCJpYXQiOjE3NjE3MjE0NjgsImp0aSI6ImQzY2E3ZjNjZGMwOTQ4NDBhZmU4ODcyYTYzNDA2NWYyIiwidXNlcl9pZCI6IjExIn0.LbqHucEJZYWkhLfwUIpGmFBFN_YHRmg7etvuSdueMXA
###
### Get CareNote by ID
GET http://127.0.0.1:8000/api/carenotes/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMTE3MTg2LCJpYXQiOjE3NjExMTUzODYsImp0aSI6IjhiMzQxZTY0MGIwMjQzMmM4YWM1N2JmMzdjNDA4MzY0IiwidXNlcl9pZCI6IjMifQ.OAirEmK4fOxZJuRMSbngPxuDC1RV2bOACEh6YF1zrcs
###
### Regenerate Summary for CareNote by ID
POST http://127.0.0.1:8000/api/carenotes/1/regenerate_summary/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMTE3MTg2LCJpYXQiOjE3NjExMTUzODYsImp0aSI6IjhiMzQxZTY0MGIwMjQzMmM4YWM1N2JmMzdjNDA4MzY0IiwidXNlcl9pZCI6IjMifQ.OAirEmK4fOxZJuRMSbngPxuDC1RV2bOACEh6YF1zrcs
### Update CareNote by ID
PUT http://127.0.0.1:8000/api/carenotes/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMTE3MTg2LCJpYXQiOjE3NjExMTUzODYsImp0aSI6IjhiMzQxZTY0MGIwMjQzMmM4YWM1N2JmMzdjNDA4MzY0IiwidXNlcl9pZCI6IjMifQ.OAirEmK4fOxZJuRMSbngPxuDC1RV2bOACEh6YF1zrcs

{
    "text": "Patient is on track to become olympian lifter.",
    "family": 3,
    "tenant": 1
}
### 
### Delete CareNote by ID
DELETE http://127.0.0.1:8000/api/carenotes/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMTE3MTg2LCJpYXQiOjE3NjExMTUzODYsImp0aSI6IjhiMzQxZTY0MGIwMjQzMmM4YWM1N2JmMzdjNDA4MzY0IiwidXNlcl9pZCI6IjMifQ.OAirEmK4fOxZJuRMSbngPxuDC1RV2bOACEh6YF1zrcs
### 
### GET CareNotes for Family Member (New Endpoint)
GET http://127.0.0.1:8000/api/family/carenotes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMTE3MTg2LCJpYXQiOjE3NjExMTUzODYsImp0aSI6IjhiMzQxZTY0MGIwMjQzMmM4YWM1N2JmMzdjNDA4MzY0IiwidXNlcl9pZCI6IjMifQ.OAirEmK4fOxZJuRMSbngPxuDC1RV2bOACEh6YF1zrcs
###