# Generated by Django 5.2.7 on 2025-10-13 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_summary_family"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summary",
            name="family",
        ),
        migrations.AddField(
            model_name="carenote",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="family",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
