# Generated by Django 5.2.7 on 2025-10-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_summary_family_carenote_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="carenote",
            name="summary_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carenote",
            name="summary_jp",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Summary",
        ),
    ]
