# Generated by Django 5.2.7 on 2025-10-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_carenote_summary_en_carenote_summary_jp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carenote",
            name="patient_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
